# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr

    http_client:
        default_options:
            cafile: '%kernel.project_dir%/config/certs/cacert.pem'

    session: true

when@dev:
    framework:
        http_client:
            default_options:
                verify_peer: false
                verify_host: false


