<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709122514 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE organisme_ffbb (id INT AUTO_INCREMENT NOT NULL, numero VARCHAR(20) NOT NULL, nom VARCHAR(180) NOT NULL, type VARCHAR(40) DEFAULT NULL, UNIQUE INDEX uniq_organisme_ffbb_numero (numero), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE action_match RENAME INDEX fk_am_joueur TO IDX_9D9509B9A9E2D76C');
        $this->addSql('ALTER TABLE action_match RENAME INDEX idx_am_session TO IDX_9D9509B9613FECDF');
        $this->addSql('ALTER TABLE action_match RENAME INDEX idx_action_assist TO IDX_9D9509B96900CDCC');
        $this->addSql('DROP INDEX IDX_affmatch_statut ON affectation_match');
        $this->addSql('ALTER TABLE affectation_match CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE affectation_match RENAME INDEX idx_affmatch_rencontre TO IDX_A668A3AD6CFC0818');
        $this->addSql('ALTER TABLE affectation_match RENAME INDEX idx_affmatch_user TO IDX_A668A3ADA76ED395');
        $this->addSql('ALTER TABLE api_token CHANGE expires_at expires_at DATETIME NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE api_token RENAME INDEX uniq_api_token_hash TO UNIQ_7BA2F5EBB3BC57DA');
        $this->addSql('ALTER TABLE api_token RENAME INDEX idx_api_token_user TO IDX_7BA2F5EBA76ED395');
        $this->addSql('ALTER TABLE bilan_competence CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE vq_respect_regles vq_respect_regles SMALLINT DEFAULT NULL, CHANGE vq_ponctualite vq_ponctualite SMALLINT DEFAULT NULL, CHANGE vq_discipline vq_discipline SMALLINT DEFAULT NULL, CHANGE vq_vie_groupe vq_vie_groupe SMALLINT DEFAULT NULL, CHANGE vq_rangement vq_rangement SMALLINT DEFAULT NULL, CHANGE qm_enthousiasme qm_enthousiasme SMALLINT DEFAULT NULL, CHANGE qm_determination qm_determination SMALLINT DEFAULT NULL, CHANGE qm_confiance qm_confiance SMALLINT DEFAULT NULL, CHANGE qm_curiosite qm_curiosite SMALLINT DEFAULT NULL, CHANGE qm_autonomie qm_autonomie SMALLINT DEFAULT NULL, CHANGE qm_concentration qm_concentration SMALLINT DEFAULT NULL, CHANGE qtt_adresse qtt_adresse SMALLINT DEFAULT NULL, CHANGE qtt_efficacite_panier qtt_efficacite_panier SMALLINT DEFAULT NULL, CHANGE qtt_aisance qtt_aisance SMALLINT DEFAULT NULL, CHANGE qtt_jeu_sans_ballons qtt_jeu_sans_ballons SMALLINT DEFAULT NULL, CHANGE qtt_comprehension qtt_comprehension SMALLINT DEFAULT NULL, CHANGE qtt_defense qtt_defense SMALLINT DEFAULT NULL, CHANGE qtt_rebond_catcher qtt_rebond_catcher SMALLINT DEFAULT NULL, CHANGE qtt_rebond_transiter qtt_rebond_transiter SMALLINT DEFAULT NULL, CHANGE qp_enchainement qp_enchainement SMALLINT DEFAULT NULL, CHANGE qp_vitesse qp_vitesse SMALLINT DEFAULT NULL, CHANGE qp_soins_du_corps qp_soins_du_corps SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE bilan_competence RENAME INDEX fk_bilan_coach TO IDX_4E203A1F3C105691');
        $this->addSql('ALTER TABLE bilan_competence RENAME INDEX idx_bilan_club TO IDX_4E203A1F61190A32');
        $this->addSql('DROP INDEX idx_bloc_contenu_page ON bloc_contenu');
        $this->addSql('ALTER TABLE bloc_contenu CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE bloc_contenu RENAME INDEX uniq_bloc_contenu_cle TO UNIQ_38D8ECB041401D17');
        $this->addSql('DROP INDEX IDX_BS_ANNEE ON bulletin_scolaire');
        $this->addSql('ALTER TABLE bulletin_scolaire CHANGE annee_scolaire annee_scolaire VARCHAR(9) NOT NULL, CHANGE trimestre trimestre VARCHAR(10) NOT NULL, CHANGE moyenne_generale moyenne_generale DOUBLE PRECISION DEFAULT NULL, CHANGE appreciation_globale appreciation_globale LONGTEXT DEFAULT NULL, CHANGE uploaded_at uploaded_at DATETIME NOT NULL, CHANGE source source VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE bulletin_scolaire RENAME INDEX idx_bs_joueur TO IDX_CE8A62C5A9E2D76C');
        $this->addSql('ALTER TABLE bulletin_scolaire RENAME INDEX fk_bs_uploaded_by TO IDX_CE8A62C5A2B28FE8');
        $this->addSql('ALTER TABLE coach_equipe CHANGE role_coach role_coach VARCHAR(30) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE coach_equipe RENAME INDEX idx_ce_user TO IDX_FFE6F1A0A76ED395');
        $this->addSql('ALTER TABLE coach_equipe RENAME INDEX idx_ce_equipe TO IDX_FFE6F1A06D861B89');
        $this->addSql('ALTER TABLE connexion_log CHANGE contexte contexte VARCHAR(30) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE connexion_log RENAME INDEX idx_cl_user TO IDX_60D817EEA76ED395');
        $this->addSql('DROP INDEX idx_cs_public ON contenu_seance');
        $this->addSql('ALTER TABLE contenu_seance CHANGE is_public_club is_public_club TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contenu_seance RENAME INDEX idx_cs_club TO IDX_7BE18D3C61190A32');
        $this->addSql('ALTER TABLE contenu_seance RENAME INDEX idx_cs_creator TO IDX_7BE18D3CB03A8386');
        $this->addSql('ALTER TABLE contenu_seance_theme RENAME INDEX fk_cst_theme TO IDX_11E4198D2DBAA019');
        $this->addSql('DROP INDEX IDX_COTI_JOUEUR_STATUT ON cotisation_joueur');
        $this->addSql('ALTER TABLE cotisation_joueur CHANGE date_paiement date_paiement DATE DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE cotisation_joueur RENAME INDEX idx_coti_joueur TO IDX_F8C58B0EA9E2D76C');
        $this->addSql('DROP INDEX IDX_DAP_STATUT ON demande_acces_pdf');
        $this->addSql('ALTER TABLE demande_acces_pdf CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE decided_at decided_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_acces_pdf RENAME INDEX idx_dap_joueur TO IDX_B8939320A9E2D76C');
        $this->addSql('ALTER TABLE demande_acces_pdf RENAME INDEX idx_dap_rencontre TO IDX_B89393206CFC0818');
        $this->addSql('ALTER TABLE demande_acces_pdf RENAME INDEX idx_dap_coach TO IDX_B89393203C105691');
        $this->addSql('DROP INDEX idx_doc_created ON document');
        $this->addSql('ALTER TABLE document CHANGE club_id club_id INT NOT NULL, CHANGE joueur_id joueur_id INT DEFAULT NULL, CHANGE uploade_par_id uploade_par_id INT DEFAULT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(50) NOT NULL, CHANGE visibilite visibilite VARCHAR(20) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE nom_original nom_original VARCHAR(255) NOT NULL, CHANGE path path VARCHAR(255) NOT NULL, CHANGE mime_type mime_type VARCHAR(100) NOT NULL, CHANGE taille taille INT NOT NULL');
        $this->addSql('ALTER TABLE document RENAME INDEX idx_doc_joueur TO IDX_D8698A76A9E2D76C');
        $this->addSql('ALTER TABLE document RENAME INDEX fk_document_uploader TO IDX_D8698A766E8D3472');
        $this->addSql('ALTER TABLE evaluation_ffbb CHANGE est_starter est_starter TINYINT NOT NULL, CHANGE minutes_jouees minutes_jouees INT NOT NULL, CHANGE points points INT NOT NULL, CHANGE tirs_2pt_reussis tirs_2pt_reussis INT NOT NULL, CHANGE tirs_2pt_tentes tirs_2pt_tentes INT NOT NULL, CHANGE tirs_3pt_reussis tirs_3pt_reussis INT NOT NULL, CHANGE tirs_3pt_tentes tirs_3pt_tentes INT NOT NULL, CHANGE lancers_reussis lancers_reussis INT NOT NULL, CHANGE lancers_tentes lancers_tentes INT NOT NULL, CHANGE rebonds_off rebonds_off INT NOT NULL, CHANGE rebonds_def rebonds_def INT NOT NULL, CHANGE passes_d passes_d INT NOT NULL, CHANGE interceptions interceptions INT NOT NULL, CHANGE contres contres INT NOT NULL, CHANGE fautes_commises fautes_commises INT NOT NULL, CHANGE pertes_balle pertes_balle INT NOT NULL, CHANGE eval_ffbb eval_ffbb INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE evaluation_ffbb RENAME INDEX idx_effbb_rencontre TO IDX_CA6286B86CFC0818');
        $this->addSql('ALTER TABLE evaluation_ffbb RENAME INDEX idx_effbb_joueur TO IDX_CA6286B8A9E2D76C');
        $this->addSql('ALTER TABLE feedback_seance CHANGE commentaire commentaire LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE feedback_seance RENAME INDEX idx_fs_seance TO IDX_E231C940E3797A94');
        $this->addSql('ALTER TABLE feedback_seance RENAME INDEX idx_fs_joueur TO IDX_E231C940A9E2D76C');
        $this->addSql('ALTER TABLE joueur CHANGE est_section_sportive est_section_sportive TINYINT NOT NULL, CHANGE is_temporaire is_temporaire TINYINT DEFAULT 0 NOT NULL, CHANGE equipe_ephemere equipe_ephemere VARCHAR(100) DEFAULT NULL, CHANGE couleur_maillot couleur_maillot VARCHAR(20) DEFAULT NULL, CHANGE rencontre_origine_id rencontre_origine_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE joueur RENAME INDEX uniq_joueur_licence TO UNIQ_FD71A9C51DAAE648');
        $this->addSql('ALTER TABLE joueur RENAME INDEX idx_joueur_rencontre_origine TO IDX_FD71A9C5871F654');
        $this->addSql('ALTER TABLE joueur_equipe CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE joueur_equipe RENAME INDEX idx_je_joueur TO IDX_CDF2AA99A9E2D76C');
        $this->addSql('ALTER TABLE joueur_equipe RENAME INDEX idx_je_equipe TO IDX_CDF2AA996D861B89');
        $this->addSql('DROP INDEX IDX_NF_CLUB_STATUT ON note_frais');
        $this->addSql('DROP INDEX IDX_NF_CLUB_DEMANDEUR ON note_frais');
        $this->addSql('ALTER TABLE note_frais CHANGE date_depense date_depense DATE NOT NULL, CHANGE date_validation date_validation DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE note_frais RENAME INDEX idx_nf_club TO IDX_4050EF4F61190A32');
        $this->addSql('ALTER TABLE note_frais RENAME INDEX idx_nf_demandeur TO IDX_4050EF4F95A6EE59');
        $this->addSql('ALTER TABLE note_frais RENAME INDEX idx_nf_validateur TO IDX_4050EF4FE57AEF2F');
        $this->addSql('ALTER TABLE note_scolaire CHANGE moyenne moyenne DOUBLE PRECISION DEFAULT NULL, CHANGE coefficient coefficient SMALLINT NOT NULL, CHANGE appreciation appreciation LONGTEXT DEFAULT NULL, CHANGE moyenne_classe moyenne_classe DOUBLE PRECISION DEFAULT NULL, CHANGE moyenne_max_classe moyenne_max_classe DOUBLE PRECISION DEFAULT NULL, CHANGE moyenne_min_classe moyenne_min_classe DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE note_scolaire RENAME INDEX idx_ns_bulletin TO IDX_ACD50A55D1AAB236');
        $this->addSql('ALTER TABLE note_seance CHANGE note note SMALLINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE note_seance RENAME INDEX idx_ns_joueur TO IDX_C7AFAADAA9E2D76C');
        $this->addSql('ALTER TABLE note_seance RENAME INDEX idx_ns_seance TO IDX_C7AFAADAE3797A94');
        $this->addSql('ALTER TABLE notification CHANGE lue lue TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE notification RENAME INDEX fk_notif_club TO IDX_BF5476CA61190A32');
        $this->addSql('DROP INDEX IDX_OP_TRESO_CLUB_DATE ON operation_tresorerie');
        $this->addSql('DROP INDEX IDX_OP_TRESO_CLUB_TYPE ON operation_tresorerie');
        $this->addSql('DROP INDEX IDX_OP_TRESO_CLUB_CAT ON operation_tresorerie');
        $this->addSql('ALTER TABLE operation_tresorerie CHANGE date date DATE NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE operation_tresorerie RENAME INDEX idx_op_treso_club TO IDX_61BB5D6561190A32');
        $this->addSql('ALTER TABLE operation_tresorerie RENAME INDEX idx_op_treso_created_by TO IDX_61BB5D65B03A8386');
        $this->addSql('ALTER TABLE operation_tresorerie RENAME INDEX uniq_op_treso_note_frais TO UNIQ_61BB5D65AF0AB15A');
        $this->addSql('DROP INDEX IDX_PI_EMAIL ON parent_invitation');
        $this->addSql('ALTER TABLE parent_invitation CHANGE created_at created_at DATETIME NOT NULL, CHANGE expires_at expires_at DATETIME NOT NULL, CHANGE accepted_at accepted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE parent_invitation RENAME INDEX idx_pi_joueur TO IDX_B65EE5F2A9E2D76C');
        $this->addSql('ALTER TABLE parent_invitation RENAME INDEX idx_pi_demandeur TO IDX_B65EE5F295A6EE59');
        $this->addSql('ALTER TABLE parent_invitation RENAME INDEX fk_pi_accepted_user TO IDX_B65EE5F22145E9FE');
        $this->addSql('DROP INDEX uniq_parent_enfant ON parent_joueur');
        $this->addSql('DROP INDEX idx_statut ON parent_joueur');
        $this->addSql('ALTER TABLE parent_joueur CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE parent_joueur RENAME INDEX idx_parent TO IDX_B2626A03D526A7D3');
        $this->addSql('ALTER TABLE parent_joueur RENAME INDEX idx_joueur TO IDX_B2626A03A9E2D76C');
        $this->addSql('ALTER TABLE parent_joueur RENAME INDEX fk_parent_valide_par TO IDX_B2626A036AF12ED9');
        $this->addSql('DROP INDEX IDX_PT_RENCONTRE_SORTIE ON presence_terrain');
        $this->addSql('DROP INDEX IDX_PT_JOUEUR_RENCONTRE ON presence_terrain');
        $this->addSql('ALTER TABLE presence_terrain CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE presence_terrain RENAME INDEX idx_pt_joueur TO IDX_D52CD264A9E2D76C');
        $this->addSql('ALTER TABLE presence_terrain RENAME INDEX idx_pt_rencontre TO IDX_D52CD2646CFC0818');
        $this->addSql('ALTER TABLE presence_terrain RENAME INDEX idx_pt_session TO IDX_D52CD264613FECDF');
        $this->addSql('DROP INDEX UNQ_R_CLUB_EQUIPE_NUMERO_SAISON ON rencontre');
        $this->addSql('ALTER TABLE rencontre CHANGE forfait_equipe forfait_equipe TINYINT NOT NULL, CHANGE forfait_adverse forfait_adverse TINYINT NOT NULL, CHANGE type_rencontre type_rencontre VARCHAR(30) NOT NULL, CHANGE joueurs_externes joueurs_externes JSON DEFAULT NULL, CHANGE ffbb_stats_validated_at ffbb_stats_validated_at DATETIME DEFAULT NULL, CHANGE mode_stats mode_stats VARCHAR(10) DEFAULT \'full\' NOT NULL');
        $this->addSql('ALTER TABLE rencontre RENAME INDEX idx_renc_ffbb_valid_by TO IDX_460C35ED23CFBF13');
        $this->addSql('ALTER TABLE reset_password_request CHANGE requested_at requested_at DATETIME NOT NULL, CHANGE expires_at expires_at DATETIME NOT NULL, CHANGE consumed_at consumed_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE reset_password_request RENAME INDEX idx_rpr_user TO IDX_7CE748AA76ED395');
        $this->addSql('DROP INDEX IDX_REUNION_DATE ON reunion');
        $this->addSql('ALTER TABLE reunion RENAME INDEX idx_reunion_club TO IDX_5B00A48261190A32');
        $this->addSql('ALTER TABLE reunion RENAME INDEX idx_reunion_createur TO IDX_5B00A48273A201E5');
        $this->addSql('ALTER TABLE reunion_convocation RENAME INDEX idx_rc_reunion TO IDX_A3D96ABF4E9B7368');
        $this->addSql('ALTER TABLE reunion_document RENAME INDEX idx_rd_uploader TO IDX_F644F69D6E8D3472');
        $this->addSql('ALTER TABLE reunion_pv_version RENAME INDEX idx_rpvv_author TO IDX_DC35837B553B2554');
        $this->addSql('DROP INDEX IDX_RGPD_STATUT ON rgpd_request');
        $this->addSql('ALTER TABLE rgpd_request CHANGE type type VARCHAR(20) NOT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE requested_at requested_at DATETIME NOT NULL, CHANGE traitee_at traitee_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE rgpd_request RENAME INDEX idx_rgpd_user TO IDX_1770BE04A76ED395');
        $this->addSql('ALTER TABLE rgpd_request RENAME INDEX idx_rgpd_traitee_par TO IDX_1770BE043338F50D');
        $this->addSql('ALTER TABLE seance CHANGE contenu_prive contenu_prive TINYINT NOT NULL');
        $this->addSql('ALTER TABLE seance RENAME INDEX idx_seance_contenu TO IDX_DF7DFD0E1210ED57');
        $this->addSql('DROP INDEX IDX_SS_STATUT ON seance_solo');
        $this->addSql('ALTER TABLE seance_solo CHANGE date_solo date_solo DATE NOT NULL, CHANGE duree_minutes duree_minutes SMALLINT NOT NULL, CHANGE type type VARCHAR(30) NOT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE validated_at validated_at DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE seance_solo RENAME INDEX idx_ss_joueur TO IDX_C39026C2A9E2D76C');
        $this->addSql('ALTER TABLE seance_solo RENAME INDEX idx_ss_validated_by TO IDX_C39026C2C69DE5E5');
        $this->addSql('DROP INDEX IDX_seance_tir_date ON seance_tir');
        $this->addSql('DROP INDEX IDX_seance_tir_source ON seance_tir');
        $this->addSql('ALTER TABLE seance_tir CHANGE rencontre_id rencontre_id INT DEFAULT NULL, CHANGE seance_id seance_id INT DEFAULT NULL, CHANGE source source VARCHAR(20) NOT NULL, CHANGE date_seance date_seance DATE NOT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL, CHANGE validated_by_coach validated_by_coach TINYINT DEFAULT 0 NOT NULL, CHANGE validated_by_id validated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE seance_tir ADD CONSTRAINT FK_3AD89FD4E3797A94 FOREIGN KEY (seance_id) REFERENCES seance (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_3AD89FD4E3797A94 ON seance_tir (seance_id)');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX idx_seance_tir_joueur TO IDX_3AD89FD4A9E2D76C');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX idx_seance_tir_club TO IDX_3AD89FD461190A32');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX idx_seance_tir_rencontre TO IDX_3AD89FD46CFC0818');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX fk_seance_tir_user TO IDX_3AD89FD4C69DE5E5');
        $this->addSql('DROP INDEX IDX_SS_RENCONTRE_STATUT ON session_stats_live');
        $this->addSql('DROP INDEX IDX_SS_CREATEDBY_STATUT ON session_stats_live');
        $this->addSql('ALTER TABLE session_stats_live CHANGE created_at created_at DATETIME NOT NULL, CHANGE completed_at completed_at DATETIME DEFAULT NULL, CHANGE promoted_at promoted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE session_stats_live RENAME INDEX idx_ss_rencontre TO IDX_F2F54FB46CFC0818');
        $this->addSql('ALTER TABLE session_stats_live RENAME INDEX idx_ss_created_by TO IDX_F2F54FB4B03A8386');
        $this->addSql('ALTER TABLE session_stats_live RENAME INDEX idx_ss_promoted_by TO IDX_F2F54FB4DBB64D3D');
        $this->addSql('DROP INDEX IDX_SUB_CLUB_SAISON ON subvention');
        $this->addSql('DROP INDEX IDX_SUB_CLUB_STATUT ON subvention');
        $this->addSql('ALTER TABLE subvention CHANGE date_depot date_depot DATE DEFAULT NULL, CHANGE date_decision date_decision DATE DEFAULT NULL, CHANGE date_touche date_touche DATE DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE subvention RENAME INDEX idx_sub_club TO IDX_CCB9393661190A32');
        $this->addSql('ALTER TABLE subvention RENAME INDEX idx_sub_created_by TO IDX_CCB93936B03A8386');
        $this->addSql('ALTER TABLE tarif_cotisation CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE tarif_cotisation RENAME INDEX idx_tarif_club TO IDX_FF89D70F61190A32');
        $this->addSql('DROP INDEX IDX_TS_GROUPE ON theme_seance');
        $this->addSql('ALTER TABLE theme_seance CHANGE is_systeme is_systeme TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE theme_seance RENAME INDEX idx_ts_club TO IDX_F45C97261190A32');
        $this->addSql('ALTER TABLE tir_ffbb CHANGE position_x position_x SMALLINT DEFAULT NULL, CHANGE position_y position_y SMALLINT DEFAULT NULL, CHANGE type_tir type_tir VARCHAR(20) DEFAULT NULL, CHANGE est_reussi est_reussi TINYINT NOT NULL, CHANGE source source VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE tir_ffbb RENAME INDEX idx_tirffbb_rencontre TO IDX_9DFABF96CFC0818');
        $this->addSql('ALTER TABLE tir_ffbb RENAME INDEX idx_tirffbb_joueur TO IDX_9DFABF9A9E2D76C');
        $this->addSql('ALTER TABLE zone_tir CHANGE position_x position_x DOUBLE PRECISION NOT NULL, CHANGE position_y position_y DOUBLE PRECISION NOT NULL, CHANGE type_tir type_tir VARCHAR(20) NOT NULL, CHANGE tentatives tentatives SMALLINT NOT NULL, CHANGE reussis reussis SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE zone_tir RENAME INDEX idx_zone_tir_seance TO IDX_8CC2E7AC921094D5');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE organisme_ffbb');
        $this->addSql('ALTER TABLE action_match RENAME INDEX idx_9d9509b96900cdcc TO IDX_ACTION_ASSIST');
        $this->addSql('ALTER TABLE action_match RENAME INDEX idx_9d9509b9a9e2d76c TO FK_AM_JOUEUR');
        $this->addSql('ALTER TABLE action_match RENAME INDEX idx_9d9509b9613fecdf TO IDX_AM_SESSION');
        $this->addSql('ALTER TABLE affectation_match CHANGE statut statut VARCHAR(20) DEFAULT \'ASSIGNE\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_affmatch_statut ON affectation_match (statut)');
        $this->addSql('ALTER TABLE affectation_match RENAME INDEX idx_a668a3ad6cfc0818 TO IDX_affmatch_rencontre');
        $this->addSql('ALTER TABLE affectation_match RENAME INDEX idx_a668a3ada76ed395 TO IDX_affmatch_user');
        $this->addSql('ALTER TABLE api_token CHANGE expires_at expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE api_token RENAME INDEX uniq_7ba2f5ebb3bc57da TO uniq_api_token_hash');
        $this->addSql('ALTER TABLE api_token RENAME INDEX idx_7ba2f5eba76ed395 TO idx_api_token_user');
        $this->addSql('ALTER TABLE bilan_competence CHANGE statut statut VARCHAR(20) DEFAULT \'brouillon\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE vq_respect_regles vq_respect_regles TINYINT DEFAULT NULL, CHANGE vq_ponctualite vq_ponctualite TINYINT DEFAULT NULL, CHANGE vq_discipline vq_discipline TINYINT DEFAULT NULL, CHANGE vq_vie_groupe vq_vie_groupe TINYINT DEFAULT NULL, CHANGE vq_rangement vq_rangement TINYINT DEFAULT NULL, CHANGE qm_enthousiasme qm_enthousiasme TINYINT DEFAULT NULL, CHANGE qm_determination qm_determination TINYINT DEFAULT NULL, CHANGE qm_confiance qm_confiance TINYINT DEFAULT NULL, CHANGE qm_curiosite qm_curiosite TINYINT DEFAULT NULL, CHANGE qm_autonomie qm_autonomie TINYINT DEFAULT NULL, CHANGE qm_concentration qm_concentration TINYINT DEFAULT NULL, CHANGE qtt_adresse qtt_adresse TINYINT DEFAULT NULL, CHANGE qtt_efficacite_panier qtt_efficacite_panier TINYINT DEFAULT NULL, CHANGE qtt_aisance qtt_aisance TINYINT DEFAULT NULL, CHANGE qtt_jeu_sans_ballons qtt_jeu_sans_ballons TINYINT DEFAULT NULL, CHANGE qtt_comprehension qtt_comprehension TINYINT DEFAULT NULL, CHANGE qtt_defense qtt_defense TINYINT DEFAULT NULL, CHANGE qtt_rebond_catcher qtt_rebond_catcher TINYINT DEFAULT NULL, CHANGE qtt_rebond_transiter qtt_rebond_transiter TINYINT DEFAULT NULL, CHANGE qp_enchainement qp_enchainement TINYINT DEFAULT NULL, CHANGE qp_vitesse qp_vitesse TINYINT DEFAULT NULL, CHANGE qp_soins_du_corps qp_soins_du_corps TINYINT DEFAULT NULL');
        $this->addSql('ALTER TABLE bilan_competence RENAME INDEX idx_4e203a1f61190a32 TO idx_bilan_club');
        $this->addSql('ALTER TABLE bilan_competence RENAME INDEX idx_4e203a1f3c105691 TO FK_bilan_coach');
        $this->addSql('ALTER TABLE bloc_contenu CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_bloc_contenu_page ON bloc_contenu (page)');
        $this->addSql('ALTER TABLE bloc_contenu RENAME INDEX uniq_38d8ecb041401d17 TO uniq_bloc_contenu_cle');
        $this->addSql('ALTER TABLE bulletin_scolaire CHANGE annee_scolaire annee_scolaire VARCHAR(9) NOT NULL COMMENT \'Ex: 2026-2027\', CHANGE trimestre trimestre VARCHAR(10) NOT NULL COMMENT \'T1, T2, T3\', CHANGE moyenne_generale moyenne_generale FLOAT DEFAULT NULL, CHANGE appreciation_globale appreciation_globale TEXT DEFAULT NULL, CHANGE uploaded_at uploaded_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE source source VARCHAR(20) DEFAULT \'manuel\' NOT NULL COMMENT \'manuel ou api_pronote ou api_ecoledirecte\'');
        $this->addSql('CREATE INDEX IDX_BS_ANNEE ON bulletin_scolaire (annee_scolaire)');
        $this->addSql('ALTER TABLE bulletin_scolaire RENAME INDEX idx_ce8a62c5a9e2d76c TO IDX_BS_JOUEUR');
        $this->addSql('ALTER TABLE bulletin_scolaire RENAME INDEX idx_ce8a62c5a2b28fe8 TO FK_BS_UPLOADED_BY');
        $this->addSql('ALTER TABLE coach_equipe CHANGE role_coach role_coach VARCHAR(30) NOT NULL COMMENT \'PRINCIPAL, ASSISTANT\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE coach_equipe RENAME INDEX idx_ffe6f1a0a76ed395 TO IDX_CE_USER');
        $this->addSql('ALTER TABLE coach_equipe RENAME INDEX idx_ffe6f1a06d861b89 TO IDX_CE_EQUIPE');
        $this->addSql('ALTER TABLE connexion_log CHANGE contexte contexte VARCHAR(30) DEFAULT NULL COMMENT \'manager, pirb, admin\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE connexion_log RENAME INDEX idx_60d817eea76ed395 TO IDX_CL_USER');
        $this->addSql('ALTER TABLE contenu_seance CHANGE is_public_club is_public_club TINYINT DEFAULT 1 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_cs_public ON contenu_seance (is_public_club)');
        $this->addSql('ALTER TABLE contenu_seance RENAME INDEX idx_7be18d3c61190a32 TO IDX_CS_CLUB');
        $this->addSql('ALTER TABLE contenu_seance RENAME INDEX idx_7be18d3cb03a8386 TO IDX_CS_CREATOR');
        $this->addSql('ALTER TABLE contenu_seance_theme RENAME INDEX idx_11e4198d2dbaa019 TO FK_CST_THEME');
        $this->addSql('ALTER TABLE cotisation_joueur CHANGE date_paiement date_paiement DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_COTI_JOUEUR_STATUT ON cotisation_joueur (joueur_id, statut)');
        $this->addSql('ALTER TABLE cotisation_joueur RENAME INDEX idx_f8c58b0ea9e2d76c TO IDX_COTI_JOUEUR');
        $this->addSql('ALTER TABLE demande_acces_pdf CHANGE statut statut VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE decided_at decided_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_DAP_STATUT ON demande_acces_pdf (statut)');
        $this->addSql('ALTER TABLE demande_acces_pdf RENAME INDEX idx_b8939320a9e2d76c TO IDX_DAP_JOUEUR');
        $this->addSql('ALTER TABLE demande_acces_pdf RENAME INDEX idx_b89393206cfc0818 TO IDX_DAP_RENCONTRE');
        $this->addSql('ALTER TABLE demande_acces_pdf RENAME INDEX idx_b89393203c105691 TO IDX_DAP_COACH');
        $this->addSql('ALTER TABLE document CHANGE titre titre VARCHAR(255) NOT NULL COMMENT \'Titre affiche dans ENT\', CHANGE type type VARCHAR(50) NOT NULL COMMENT \'COMPTE_RENDU | PLANNING | REGLEMENT | FORMULAIRE | DOCUMENT_JOUEUR | MEDIA | CONVOCATION | AUTRE\', CHANGE visibilite visibilite VARCHAR(20) NOT NULL COMMENT \'STAFF | MEMBRES | PARENTS\', CHANGE description description LONGTEXT DEFAULT NULL COMMENT \'Description optionnelle\', CHANGE nom_original nom_original VARCHAR(255) NOT NULL COMMENT \'Nom original du fichier cote utilisateur\', CHANGE path path VARCHAR(255) NOT NULL COMMENT \'Chemin relatif dans uploads/ent/{clubId}/\', CHANGE mime_type mime_type VARCHAR(100) NOT NULL COMMENT \'MIME type valide a upload\', CHANGE taille taille INT DEFAULT 0 NOT NULL COMMENT \'Taille en octets\', CHANGE club_id club_id INT NOT NULL COMMENT \'Club propriétaire (multi-tenant)\', CHANGE joueur_id joueur_id INT DEFAULT NULL COMMENT \'Joueuse concernée (optionnel)\', CHANGE uploade_par_id uploade_par_id INT DEFAULT NULL COMMENT \'User qui a uploadé\'');
        $this->addSql('CREATE INDEX idx_doc_created ON document (created_at)');
        $this->addSql('ALTER TABLE document RENAME INDEX idx_d8698a766e8d3472 TO FK_document_uploader');
        $this->addSql('ALTER TABLE document RENAME INDEX idx_d8698a76a9e2d76c TO idx_doc_joueur');
        $this->addSql('ALTER TABLE evaluation_ffbb CHANGE est_starter est_starter TINYINT DEFAULT 0 NOT NULL, CHANGE minutes_jouees minutes_jouees INT DEFAULT 0 NOT NULL, CHANGE points points INT DEFAULT 0 NOT NULL, CHANGE tirs_2pt_reussis tirs_2pt_reussis INT DEFAULT 0 NOT NULL, CHANGE tirs_2pt_tentes tirs_2pt_tentes INT DEFAULT 0 NOT NULL, CHANGE tirs_3pt_reussis tirs_3pt_reussis INT DEFAULT 0 NOT NULL, CHANGE tirs_3pt_tentes tirs_3pt_tentes INT DEFAULT 0 NOT NULL, CHANGE lancers_reussis lancers_reussis INT DEFAULT 0 NOT NULL, CHANGE lancers_tentes lancers_tentes INT DEFAULT 0 NOT NULL, CHANGE rebonds_off rebonds_off INT DEFAULT 0 NOT NULL, CHANGE rebonds_def rebonds_def INT DEFAULT 0 NOT NULL, CHANGE passes_d passes_d INT DEFAULT 0 NOT NULL, CHANGE interceptions interceptions INT DEFAULT 0 NOT NULL, CHANGE contres contres INT DEFAULT 0 NOT NULL, CHANGE fautes_commises fautes_commises INT DEFAULT 0 NOT NULL, CHANGE pertes_balle pertes_balle INT DEFAULT 0 NOT NULL, CHANGE eval_ffbb eval_ffbb INT DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE evaluation_ffbb RENAME INDEX idx_ca6286b86cfc0818 TO IDX_EFFBB_RENCONTRE');
        $this->addSql('ALTER TABLE evaluation_ffbb RENAME INDEX idx_ca6286b8a9e2d76c TO IDX_EFFBB_JOUEUR');
        $this->addSql('ALTER TABLE feedback_seance CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE feedback_seance RENAME INDEX idx_e231c940e3797a94 TO IDX_FS_SEANCE');
        $this->addSql('ALTER TABLE feedback_seance RENAME INDEX idx_e231c940a9e2d76c TO IDX_FS_JOUEUR');
        $this->addSql('ALTER TABLE joueur CHANGE is_temporaire is_temporaire TINYINT DEFAULT 0 NOT NULL COMMENT \'Joueuse créée rapidement pour une rencontre (recrutement, open gym)\', CHANGE equipe_ephemere equipe_ephemere VARCHAR(100) DEFAULT NULL COMMENT \'NULL = notre équipe, STRING = nom équipe adverse\', CHANGE couleur_maillot couleur_maillot VARCHAR(20) DEFAULT NULL COMMENT \'Couleur de maillot pour distinguer en stats live (#hex ou nom)\', CHANGE est_section_sportive est_section_sportive TINYINT DEFAULT 0 NOT NULL, CHANGE rencontre_origine_id rencontre_origine_id INT DEFAULT NULL COMMENT \'FK rencontre ayant créé cette joueuse éphémère\'');
        $this->addSql('ALTER TABLE joueur RENAME INDEX uniq_fd71a9c51daae648 TO uniq_joueur_licence');
        $this->addSql('ALTER TABLE joueur RENAME INDEX idx_fd71a9c5871f654 TO IDX_joueur_rencontre_origine');
        $this->addSql('ALTER TABLE joueur_equipe CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE joueur_equipe RENAME INDEX idx_cdf2aa99a9e2d76c TO IDX_JE_JOUEUR');
        $this->addSql('ALTER TABLE joueur_equipe RENAME INDEX idx_cdf2aa996d861b89 TO IDX_JE_EQUIPE');
        $this->addSql('ALTER TABLE note_frais CHANGE date_depense date_depense DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE date_validation date_validation DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_NF_CLUB_STATUT ON note_frais (club_id, statut)');
        $this->addSql('CREATE INDEX IDX_NF_CLUB_DEMANDEUR ON note_frais (club_id, demandeur_id)');
        $this->addSql('ALTER TABLE note_frais RENAME INDEX idx_4050ef4f61190a32 TO IDX_NF_CLUB');
        $this->addSql('ALTER TABLE note_frais RENAME INDEX idx_4050ef4f95a6ee59 TO IDX_NF_DEMANDEUR');
        $this->addSql('ALTER TABLE note_frais RENAME INDEX idx_4050ef4fe57aef2f TO IDX_NF_VALIDATEUR');
        $this->addSql('ALTER TABLE note_scolaire CHANGE moyenne moyenne FLOAT DEFAULT NULL, CHANGE coefficient coefficient SMALLINT DEFAULT 1 NOT NULL, CHANGE appreciation appreciation TEXT DEFAULT NULL, CHANGE moyenne_classe moyenne_classe FLOAT DEFAULT NULL, CHANGE moyenne_max_classe moyenne_max_classe FLOAT DEFAULT NULL, CHANGE moyenne_min_classe moyenne_min_classe FLOAT DEFAULT NULL');
        $this->addSql('ALTER TABLE note_scolaire RENAME INDEX idx_acd50a55d1aab236 TO IDX_NS_BULLETIN');
        $this->addSql('ALTER TABLE note_seance CHANGE note note SMALLINT DEFAULT 3 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE note_seance RENAME INDEX idx_c7afaadaa9e2d76c TO IDX_NS_JOUEUR');
        $this->addSql('ALTER TABLE note_seance RENAME INDEX idx_c7afaadae3797a94 TO IDX_NS_SEANCE');
        $this->addSql('ALTER TABLE notification CHANGE lue lue TINYINT DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE notification RENAME INDEX idx_bf5476ca61190a32 TO FK_notif_club');
        $this->addSql('ALTER TABLE operation_tresorerie CHANGE date date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_OP_TRESO_CLUB_DATE ON operation_tresorerie (club_id, date)');
        $this->addSql('CREATE INDEX IDX_OP_TRESO_CLUB_TYPE ON operation_tresorerie (club_id, type)');
        $this->addSql('CREATE INDEX IDX_OP_TRESO_CLUB_CAT ON operation_tresorerie (club_id, categorie)');
        $this->addSql('ALTER TABLE operation_tresorerie RENAME INDEX uniq_61bb5d65af0ab15a TO UNIQ_OP_TRESO_NOTE_FRAIS');
        $this->addSql('ALTER TABLE operation_tresorerie RENAME INDEX idx_61bb5d6561190a32 TO IDX_OP_TRESO_CLUB');
        $this->addSql('ALTER TABLE operation_tresorerie RENAME INDEX idx_61bb5d65b03a8386 TO IDX_OP_TRESO_CREATED_BY');
        $this->addSql('ALTER TABLE parent_invitation CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE expires_at expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE accepted_at accepted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_PI_EMAIL ON parent_invitation (email_cible)');
        $this->addSql('ALTER TABLE parent_invitation RENAME INDEX idx_b65ee5f2a9e2d76c TO IDX_PI_JOUEUR');
        $this->addSql('ALTER TABLE parent_invitation RENAME INDEX idx_b65ee5f295a6ee59 TO IDX_PI_DEMANDEUR');
        $this->addSql('ALTER TABLE parent_invitation RENAME INDEX idx_b65ee5f22145e9fe TO FK_PI_ACCEPTED_USER');
        $this->addSql('ALTER TABLE parent_joueur CHANGE statut statut VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_parent_enfant ON parent_joueur (parent_user_id, joueur_id)');
        $this->addSql('CREATE INDEX idx_statut ON parent_joueur (statut)');
        $this->addSql('ALTER TABLE parent_joueur RENAME INDEX idx_b2626a03d526a7d3 TO idx_parent');
        $this->addSql('ALTER TABLE parent_joueur RENAME INDEX idx_b2626a03a9e2d76c TO idx_joueur');
        $this->addSql('ALTER TABLE parent_joueur RENAME INDEX idx_b2626a036af12ed9 TO fk_parent_valide_par');
        $this->addSql('ALTER TABLE presence_terrain CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_PT_RENCONTRE_SORTIE ON presence_terrain (rencontre_id, secondes_sortie)');
        $this->addSql('CREATE INDEX IDX_PT_JOUEUR_RENCONTRE ON presence_terrain (joueur_id, rencontre_id)');
        $this->addSql('ALTER TABLE presence_terrain RENAME INDEX idx_d52cd264a9e2d76c TO IDX_PT_JOUEUR');
        $this->addSql('ALTER TABLE presence_terrain RENAME INDEX idx_d52cd2646cfc0818 TO IDX_PT_RENCONTRE');
        $this->addSql('ALTER TABLE presence_terrain RENAME INDEX idx_d52cd264613fecdf TO IDX_PT_SESSION');
        $this->addSql('ALTER TABLE rencontre CHANGE type_rencontre type_rencontre VARCHAR(30) DEFAULT \'OFFICIEL\' NOT NULL, CHANGE mode_stats mode_stats VARCHAR(10) DEFAULT \'full\' NOT NULL COMMENT \'full=stats complètes, light=points+rebonds+passes, none=sans stats\', CHANGE joueurs_externes joueurs_externes JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE forfait_equipe forfait_equipe TINYINT DEFAULT 0 NOT NULL, CHANGE forfait_adverse forfait_adverse TINYINT DEFAULT 0 NOT NULL, CHANGE ffbb_stats_validated_at ffbb_stats_validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX UNQ_R_CLUB_EQUIPE_NUMERO_SAISON ON rencontre (club_id, equipe_id, numero_match, saison)');
        $this->addSql('ALTER TABLE rencontre RENAME INDEX idx_460c35ed23cfbf13 TO IDX_RENC_FFBB_VALID_BY');
        $this->addSql('ALTER TABLE reset_password_request CHANGE requested_at requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE expires_at expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE consumed_at consumed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE reset_password_request RENAME INDEX idx_7ce748aa76ed395 TO IDX_RPR_USER');
        $this->addSql('CREATE INDEX IDX_REUNION_DATE ON reunion (date)');
        $this->addSql('ALTER TABLE reunion RENAME INDEX idx_5b00a48261190a32 TO IDX_REUNION_CLUB');
        $this->addSql('ALTER TABLE reunion RENAME INDEX idx_5b00a48273a201e5 TO IDX_REUNION_CREATEUR');
        $this->addSql('ALTER TABLE reunion_convocation RENAME INDEX idx_a3d96abf4e9b7368 TO IDX_RC_REUNION');
        $this->addSql('ALTER TABLE reunion_document RENAME INDEX idx_f644f69d6e8d3472 TO IDX_RD_UPLOADER');
        $this->addSql('ALTER TABLE reunion_pv_version RENAME INDEX idx_dc35837b553b2554 TO IDX_RPVV_AUTHOR');
        $this->addSql('ALTER TABLE rgpd_request CHANGE type type VARCHAR(20) NOT NULL COMMENT \'effacement, export\', CHANGE statut statut VARCHAR(20) NOT NULL COMMENT \'pending, validee, effectuee, refusee\', CHANGE requested_at requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE traitee_at traitee_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_RGPD_STATUT ON rgpd_request (statut)');
        $this->addSql('ALTER TABLE rgpd_request RENAME INDEX idx_1770be04a76ed395 TO IDX_RGPD_USER');
        $this->addSql('ALTER TABLE rgpd_request RENAME INDEX idx_1770be043338f50d TO IDX_RGPD_TRAITEE_PAR');
        $this->addSql('ALTER TABLE seance CHANGE contenu_prive contenu_prive TINYINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE seance RENAME INDEX idx_df7dfd0e1210ed57 TO IDX_SEANCE_CONTENU');
        $this->addSql('ALTER TABLE seance_solo CHANGE date_solo date_solo DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE duree_minutes duree_minutes SMALLINT DEFAULT 60 NOT NULL, CHANGE type type VARCHAR(30) DEFAULT \'Shoot\' NOT NULL, CHANGE statut statut VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE validated_at validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_SS_STATUT ON seance_solo (statut)');
        $this->addSql('ALTER TABLE seance_solo RENAME INDEX idx_c39026c2a9e2d76c TO IDX_SS_JOUEUR');
        $this->addSql('ALTER TABLE seance_solo RENAME INDEX idx_c39026c2c69de5e5 TO IDX_SS_VALIDATED_BY');
        $this->addSql('ALTER TABLE seance_tir DROP FOREIGN KEY FK_3AD89FD4E3797A94');
        $this->addSql('DROP INDEX IDX_3AD89FD4E3797A94 ON seance_tir');
        $this->addSql('ALTER TABLE seance_tir CHANGE source source VARCHAR(20) NOT NULL COMMENT \'ENTRAINEMENT | MATCH\', CHANGE date_seance date_seance DATE NOT NULL COMMENT \'Date de la séance de tir\', CHANGE notes notes TEXT DEFAULT NULL COMMENT \'Notes libres (contexte, conditions...)\', CHANGE validated_by_coach validated_by_coach TINYINT DEFAULT 0 NOT NULL COMMENT \'Validé par un coach (requis pour ENTRAINEMENT)\', CHANGE rencontre_id rencontre_id INT DEFAULT NULL COMMENT \'Rencontre liée (si source=MATCH)\', CHANGE seance_id seance_id INT DEFAULT NULL COMMENT \'Séance liée (si source=ENTRAINEMENT, optionnel)\', CHANGE validated_by_id validated_by_id INT DEFAULT NULL COMMENT \'FK User coach qui a validé\'');
        $this->addSql('CREATE INDEX IDX_seance_tir_date ON seance_tir (date_seance)');
        $this->addSql('CREATE INDEX IDX_seance_tir_source ON seance_tir (source)');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX idx_3ad89fd4c69de5e5 TO FK_seance_tir_user');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX idx_3ad89fd4a9e2d76c TO IDX_seance_tir_joueur');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX idx_3ad89fd461190a32 TO IDX_seance_tir_club');
        $this->addSql('ALTER TABLE seance_tir RENAME INDEX idx_3ad89fd46cfc0818 TO IDX_seance_tir_rencontre');
        $this->addSql('ALTER TABLE session_stats_live CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE completed_at completed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE promoted_at promoted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_SS_RENCONTRE_STATUT ON session_stats_live (rencontre_id, statut)');
        $this->addSql('CREATE INDEX IDX_SS_CREATEDBY_STATUT ON session_stats_live (created_by_id, statut)');
        $this->addSql('ALTER TABLE session_stats_live RENAME INDEX idx_f2f54fb46cfc0818 TO IDX_SS_RENCONTRE');
        $this->addSql('ALTER TABLE session_stats_live RENAME INDEX idx_f2f54fb4b03a8386 TO IDX_SS_CREATED_BY');
        $this->addSql('ALTER TABLE session_stats_live RENAME INDEX idx_f2f54fb4dbb64d3d TO IDX_SS_PROMOTED_BY');
        $this->addSql('ALTER TABLE subvention CHANGE date_depot date_depot DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE date_decision date_decision DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE date_touche date_touche DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_SUB_CLUB_SAISON ON subvention (club_id, saison)');
        $this->addSql('CREATE INDEX IDX_SUB_CLUB_STATUT ON subvention (club_id, statut)');
        $this->addSql('ALTER TABLE subvention RENAME INDEX idx_ccb9393661190a32 TO IDX_SUB_CLUB');
        $this->addSql('ALTER TABLE subvention RENAME INDEX idx_ccb93936b03a8386 TO IDX_SUB_CREATED_BY');
        $this->addSql('ALTER TABLE tarif_cotisation CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE tarif_cotisation RENAME INDEX idx_ff89d70f61190a32 TO IDX_TARIF_CLUB');
        $this->addSql('ALTER TABLE theme_seance CHANGE is_systeme is_systeme TINYINT DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_TS_GROUPE ON theme_seance (groupe)');
        $this->addSql('ALTER TABLE theme_seance RENAME INDEX idx_f45c97261190a32 TO IDX_TS_CLUB');
        $this->addSql('ALTER TABLE tir_ffbb CHANGE position_x position_x SMALLINT DEFAULT NULL COMMENT \'X 0-100 % du terrain\', CHANGE position_y position_y SMALLINT DEFAULT NULL COMMENT \'Y 0-100 % du terrain\', CHANGE type_tir type_tir VARCHAR(20) DEFAULT NULL COMMENT \'2pt_int, 2pt_ext, 3pt\', CHANGE est_reussi est_reussi TINYINT DEFAULT 1 NOT NULL, CHANGE source source VARCHAR(20) DEFAULT \'ffbb\' NOT NULL COMMENT \'ffbb ou stats_live\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE tir_ffbb RENAME INDEX idx_9dfabf96cfc0818 TO IDX_TIRFFBB_RENCONTRE');
        $this->addSql('ALTER TABLE tir_ffbb RENAME INDEX idx_9dfabf9a9e2d76c TO IDX_TIRFFBB_JOUEUR');
        $this->addSql('ALTER TABLE zone_tir CHANGE position_x position_x DOUBLE PRECISION NOT NULL COMMENT \'Position X normalisée 0-1 (gauche=0, droite=1)\', CHANGE position_y position_y DOUBLE PRECISION NOT NULL COMMENT \'Position Y normalisée 0-1 (fond=0, milieu=1)\', CHANGE type_tir type_tir VARCHAR(20) NOT NULL COMMENT \'2pt_int | 2pt_ext | 3pt | lancer\', CHANGE tentatives tentatives SMALLINT DEFAULT 1 NOT NULL, CHANGE reussis reussis SMALLINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE zone_tir RENAME INDEX idx_8cc2e7ac921094d5 TO IDX_zone_tir_seance');
    }
}
